services:
  - type: web
    name: spotter-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn spotter.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "spotter-eemr.onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.3"