# Generated by Django 5.2.10 on 2026-02-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0003_alter_user_plan_options_alter_userdata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="workout_videos/")),
            ],
        ),
    ]
