# Generated by Django 5.2.10 on 2026-02-19 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0006_exercise"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={"verbose_name_plural": "Exercises"},
        ),
    ]
