# Generated by Django 5.2.10 on 2026-02-20 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0010_alter_exercise_options_exercise_order_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={"ordering": ["order_index"], "verbose_name_plural": "Exercises"},
        ),
    ]
