# Generated by Django 5.2.10 on 2026-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0014_rename_exercise1_image_exercise_exercise_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="order_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
