# Generated by Django 5.2.10 on 2026-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0015_alter_exercise_order_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="order_index",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
