# Generated by Django 5.2.10 on 2026-02-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0016_alter_exercise_order_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="exercise_image",
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise1_image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise1_pics/"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise2_image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise2_pics/"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise3_image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise3_pics/"),
        ),
    ]
