# Generated by Django 5.2.10 on 2026-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0017_remove_exercise_exercise_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="exercise1_image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise_pics/"),
        ),
    ]
