# Generated by Django 5.2.10 on 2026-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fitness",
            "0022_remove_diet_dairy_sources_remove_diet_fruits_sources_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="diet",
            name="c_image",
            field=models.ImageField(blank=True, null=True, upload_to="c_pics/"),
        ),
        migrations.AddField(
            model_name="diet",
            name="fa_image",
            field=models.ImageField(blank=True, null=True, upload_to="fa_pics/"),
        ),
        migrations.AddField(
            model_name="diet",
            name="fi_image",
            field=models.ImageField(blank=True, null=True, upload_to="fi_pics/"),
        ),
        migrations.AddField(
            model_name="diet",
            name="p_image",
            field=models.ImageField(blank=True, null=True, upload_to="p_pics/"),
        ),
        migrations.AddField(
            model_name="diet",
            name="vm_image",
            field=models.ImageField(blank=True, null=True, upload_to="vm_pics/"),
        ),
    ]
