# Generated by Django 5.2.10 on 2026-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0023_diet_c_image_diet_fa_image_diet_fi_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_posts"),
        ),
    ]
