# Generated by Django 5.2.10 on 2026-02-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0025_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
