# Generated by Django 5.2.10 on 2026-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0026_alter_post_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyBuilding",
            fields=[
                (
                    "game",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "game_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="body_building/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gymnastics",
            fields=[
                (
                    "game",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "game_img",
                    models.ImageField(blank=True, null=True, upload_to="gymnastics/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PowerLifting",
            fields=[
                (
                    "game",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "game_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="power_lifting/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrongMan",
            fields=[
                (
                    "game",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "game_img",
                    models.ImageField(blank=True, null=True, upload_to="strong_man/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackField",
            fields=[
                (
                    "game",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "game_img",
                    models.ImageField(blank=True, null=True, upload_to="track_field/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightLifting",
            fields=[
                (
                    "game",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "game_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="weight_lifting/"
                    ),
                ),
            ],
        ),
    ]
