# Generated by Django 5.2.10 on 2026-03-01 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0030_courses"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Courses",
            new_name="Course",
        ),
    ]
