# Generated by Django 5.2.10 on 2026-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0032_course_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=100000)),
                ("name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=1000)),
            ],
        ),
    ]
