# Generated by Django 5.2.10 on 2026-02-16 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user_plan",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userdata",
            options={},
        ),
        migrations.AlterModelTable(
            name="bodybuildingplan",
            table="bodybuilding_plan",
        ),
        migrations.AlterModelTable(
            name="musclegainplan",
            table="muscle_gain_plan",
        ),
        migrations.AlterModelTable(
            name="weightlossplan",
            table="weight_loss_plan",
        ),
    ]
