# Generated by Django 5.2.10 on 2026-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0004_exercisevideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisevideo",
            name="video_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
