# Generated by Django 5.2.10 on 2026-02-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0005_exercisevideo_video_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "target_muscle",
                    models.CharField(
                        help_text="The specific muscle group being targeted.",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dumbbell",
                    models.CharField(max_length=255, verbose_name="Dumbbell Exercise"),
                ),
                (
                    "barbell",
                    models.CharField(max_length=255, verbose_name="Barbell Exercise"),
                ),
                (
                    "machine_cable",
                    models.CharField(
                        max_length=255, verbose_name="Machine/Cable Exercise"
                    ),
                ),
                (
                    "bodyweight_other",
                    models.CharField(
                        max_length=255, verbose_name="Bodyweight/Other Exercise"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Exercises",
                "ordering": ["target_muscle"],
            },
        ),
    ]
