# Generated by Django 5.2.10 on 2026-02-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0007_alter_exercise_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="exercise_gif",
            field=models.ImageField(blank=True, null=True, upload_to="exercise_gifs/"),
        ),
    ]
