# Generated by Django 5.2.10 on 2026-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0008_exercise_exercise_gif"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="exercise_gif",
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise_image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise_pics/"),
        ),
    ]
