# Generated by Django 5.2.10 on 2026-02-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0009_remove_exercise_exercise_gif_exercise_exercise_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={"ordering": ["target_muscle"], "verbose_name_plural": "Exercises"},
        ),
        migrations.AddField(
            model_name="exercise",
            name="order_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
