# Generated by Django 5.2.10 on 2026-02-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0011_alter_exercise_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="exercise_image",
            new_name="exercise1_image",
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise2_image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise_pics/"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise3_image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise_pics/"),
        ),
    ]
