# Generated by Django 5.2.10 on 2026-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0012_rename_exercise_image_exercise_exercise1_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="order_index",
            field=models.IntegerField(),
        ),
    ]
