# Generated by Django 5.2.10 on 2026-02-20 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0013_alter_exercise_order_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="exercise1_image",
            new_name="exercise_image",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="exercise2_image",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="exercise3_image",
        ),
    ]
