# Generated by Django 5.2.10 on 2026-02-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0018_alter_exercise_exercise1_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="exercise4_image",
            field=models.ImageField(blank=True, null=True, upload_to="exercise4_pics/"),
        ),
    ]
