# Generated by Django 5.2.10 on 2026-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0019_exercise_exercise4_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.IntegerField(blank=True, default=0, null=True)),
                ("nutrient_name", models.CharField(max_length=100)),
                ("veg_sources", models.TextField(blank=True, null=True)),
                ("non_veg_sources", models.TextField(blank=True, null=True)),
                ("dairy_sources", models.TextField(blank=True, null=True)),
                ("nuts_seeds_sources", models.TextField(blank=True, null=True)),
                ("fruits_sources", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
