# Generated by Django 5.2.10 on 2026-02-23 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0020_diet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diet",
            name="order_index",
        ),
    ]
