# Generated by Django 5.2.10 on 2026-02-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0021_remove_diet_order_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diet",
            name="dairy_sources",
        ),
        migrations.RemoveField(
            model_name="diet",
            name="fruits_sources",
        ),
        migrations.RemoveField(
            model_name="diet",
            name="non_veg_sources",
        ),
        migrations.RemoveField(
            model_name="diet",
            name="nutrient_name",
        ),
        migrations.RemoveField(
            model_name="diet",
            name="nuts_seeds_sources",
        ),
        migrations.RemoveField(
            model_name="diet",
            name="veg_sources",
        ),
        migrations.AddField(
            model_name="diet",
            name="carbs",
            field=models.TextField(default="—"),
        ),
        migrations.AddField(
            model_name="diet",
            name="category",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diet",
            name="fats",
            field=models.TextField(default="—"),
        ),
        migrations.AddField(
            model_name="diet",
            name="fiber",
            field=models.TextField(default="—"),
        ),
        migrations.AddField(
            model_name="diet",
            name="protein",
            field=models.TextField(default="—"),
        ),
        migrations.AddField(
            model_name="diet",
            name="vitamins_minerals",
            field=models.TextField(default="—"),
        ),
    ]
