# Generated by Django 5.2.10 on 2026-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0024_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
