# Generated by Django 5.2.10 on 2026-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0027_bodybuilding_gymnastics_powerlifting_strongman_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodybuilding",
            name="lifting_sport",
            field=models.CharField(default="Body Building", max_length=20),
        ),
        migrations.AddField(
            model_name="gymnastics",
            name="lifting_sport",
            field=models.CharField(default="Gymnastics", max_length=20),
        ),
        migrations.AddField(
            model_name="powerlifting",
            name="lifting_sport",
            field=models.CharField(default="Power Lifting", max_length=20),
        ),
        migrations.AddField(
            model_name="strongman",
            name="lifting_sport",
            field=models.CharField(default="Strong Man", max_length=20),
        ),
        migrations.AddField(
            model_name="trackfield",
            name="lifting_sport",
            field=models.CharField(default="Track & Field", max_length=20),
        ),
        migrations.AddField(
            model_name="weightlifting",
            name="lifting_sport",
            field=models.CharField(default="Weight Lifting", max_length=20),
        ),
    ]
