# Generated by Django 5.2.10 on 2026-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fitness",
            "0028_bodybuilding_lifting_sport_gymnastics_lifting_sport_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bodybuilding",
            name="description",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="gymnastics",
            name="description",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="powerlifting",
            name="description",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="strongman",
            name="description",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="trackfield",
            name="description",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="weightlifting",
            name="description",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
