# Generated by Django 5.2.10 on 2026-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0029_bodybuilding_description_gymnastics_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_target", models.CharField(max_length=20)),
                ("info", models.CharField(max_length=1000)),
                ("purpose", models.CharField(max_length=1000)),
                ("planning", models.CharField(max_length=1000)),
            ],
        ),
    ]
