# Generated by Django 5.2.10 on 2026-03-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0031_rename_courses_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="img",
            field=models.ImageField(default=0, upload_to="target/"),
            preserve_default=False,
        ),
    ]
